apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-argocd-helm
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://jerrybaijy.github.io/k8s-argocd-helm/
    targetRevision: 0.1.0
    path: /
    chart: front-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-argocd-helm

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true